### ISSUE TITLE
MVP tracking for 1.0

### ISSUE THREAD

**Issue by HybridEidolon** [BygoneWorlds/telepipe#1]
The minimum features necessary for a 1.0 release.
## Requirements
- PSO Episode 3, all regions, must be playable on schtserv (If 1&2 work, that's great, but not MVP)
- Must allow connection through Dolphin (instructing the user to set client bind IP to the virtual NIC's host IP, DNS to host IP on virtual network)
## Task list
- [x] Port GC stream cipher to Rust
- [x] Basic message buffer parsing (Unknown variant)
- [x] Welcome and Redirect parsing
  - [x] Welcome
  - [x] Redirect
- [x] Connection handler
  - [x] Handle special-case messages (Welcome, Redirect)
- [x] Minimum DNS server emulation (respond with host virtual IP for all requests)
